{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jetbrains.compose",
    "module": "compose-gradle-plugin",
    "version": "1.2.0-alpha-custom",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        }
      ],
      "files": [
        {
          "name": "compose-gradle-plugin-1.2.0-alpha-custom.jar",
          "url": "compose-gradle-plugin-1.2.0-alpha-custom.jar",
          "size": 4312035,
          "sha512": "afcd2f16dee3f8a93d8068a30a80e6ef0103e9ae4e342e6d9d273526a989f5c92fcfd03af655d2a07bcc40912ada485a051f73e878d1050f3b7bd1d98c65c360",
          "sha256": "fe9036e7e5a3638e207ef9ed7a2f87586b4c48ba5c7e3b386265359c2e18aefe",
          "sha1": "be0071daf5f660ec929cdebcbe713162d8308827",
          "md5": "d44e4067495e0a5447a7a361aa30e563"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.30"
          }
        }
      ],
      "files": [
        {
          "name": "compose-gradle-plugin-1.2.0-alpha-custom.jar",
          "url": "compose-gradle-plugin-1.2.0-alpha-custom.jar",
          "size": 4312035,
          "sha512": "afcd2f16dee3f8a93d8068a30a80e6ef0103e9ae4e342e6d9d273526a989f5c92fcfd03af655d2a07bcc40912ada485a051f73e878d1050f3b7bd1d98c65c360",
          "sha256": "fe9036e7e5a3638e207ef9ed7a2f87586b4c48ba5c7e3b386265359c2e18aefe",
          "sha1": "be0071daf5f660ec929cdebcbe713162d8308827",
          "md5": "d44e4067495e0a5447a7a361aa30e563"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "compose-gradle-plugin-1.2.0-alpha-custom-javadoc.jar",
          "url": "compose-gradle-plugin-1.2.0-alpha-custom-javadoc.jar",
          "size": 261,
          "sha512": "27f40d8b0ce550a9ed3a361bd590a433fd58db2493af2e2e51ff237562c16fbc31379be786bb37e6f16b73e248eb420f029a7cddbf33123bfa0e0faee2eacf2e",
          "sha256": "7b828325cc49a8f9df3c3fa5d307ce30ea84c8c9b0b822c7116c9603e44d4368",
          "sha1": "00c37b8f49ff385aa08302c5690a69c640f8cc3e",
          "md5": "b779212574200d2db08902f7bf982198"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "compose-gradle-plugin-1.2.0-alpha-custom-sources.jar",
          "url": "compose-gradle-plugin-1.2.0-alpha-custom-sources.jar",
          "size": 601356,
          "sha512": "a3978229deb62cc47b4b47fa85e3a14e44e45d2ce02fda1944827e4f3520cb493b5e0d4485eb2941b3c7d974bfe7178321e7672f72ff58c9806f30ed717e42a1",
          "sha256": "4d3b263871ceb444e22c4e58c38e8a6c3f79edc9da31720521da243e857f787f",
          "sha1": "b5d9904765f2684627815a39fa8f354ae6453385",
          "md5": "1c490ccf17557a883f6ca4b7de6c3941"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "compose-gradle-plugin-1.2.0-alpha-custom-shadow.jar",
          "url": "compose-gradle-plugin-1.2.0-alpha-custom-shadow.jar",
          "size": 3253036,
          "sha512": "f2485bdbae9458de8773c2459f9c9b613814d8793159c0eeff958f5694c76941be54940d63f00a4abaa8817d3aa208c885030feb4d2a21c95d8240721bd5d73d",
          "sha256": "4658fd7425cfbb27d4d47068a9a2f1a55ceacdaacda9eb91813a3c845234a40a",
          "sha1": "3abbb84278a8d2054fb0f3d87fe938fa48f83d7f",
          "md5": "97b6c97cae4babb9ff642c0fa7551f50"
        }
      ]
    }
  ]
}
